### ISSUE TITLE
discontinued?

### ISSUE THREAD

**Issue by Melon-The-Dev** [Jaagrav/CodeX-API#46]
is this discontinued cuz its says that the *service has been suspended*

**Comment by Gyash2112** [comment]
Yes i am also facing the same issue......Service has been suspended

**Comment by KingpinDk** [comment]
yeah same here do anybody know free api for online code compilation

**Comment by Melon-The-Dev** [comment]
> yeah same here do anybody know free api for online code compilation

oh yeah! i found one and its called paiza( api.paiza.io is the api docs link i think )

**Comment by Jaagrav** [comment]
The API should be back now. 

Let me be clear here, the reason why I made this project was for an interview assignment for getting into one of the orgs I previously worked at. And the reason why I made this opensource was so that people are not dependent on my API rather they read how to setup this API and deploy it themselves. The docs are right here in the same repo, but you folks choose to use APIs hosted by third party instead of learning how to run this one yourself. As developers learn to not be dependent on APIs run by other indie developers who have to pay out of their own pocket to keep an API running that makes no profit at all but gets over 100k requests a month. 

That being said I am planning on making this API freemium which means there would be a free version always available but with a limit. I'll suggest you to checkout the [RapidAPI listing](https://rapidapi.com/jaagravseal03/api/codex7), the free listing is already out there, if this API needs to stay running it has to pay for itself somehow, money doesn't grow on trees 😂.

And as for the current endpoint, `api.codex.jaagrav.in`, it will be deprecated by September 31, 2023. If you want to continue using CodeX, check out the API listing, if not then you can host it yourself in a docker container using whatever hosting service works for you best or you can go for some other API.

**Comment by BanDroid** [comment]
your project is amazing sir 🔥 i learned a lot by this project and inspired to create my own.

users that using my plugin are satisfied with this service, thank you.
